services:
  app_dev:
    build:
      context: .
      target: builder
      args:
        - NODE_ENV=development
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - build:/app/build
    environment:
      - NODE_ENV=development
      - GENERATE_SOURCEMAP=false
      - NODE_OPTIONS=--max_old_space_size=4096
      - NPM_CONFIG_LEGACY_PEER_DEPS=true
      - NPM_CONFIG_FORCE=true
    ports:
      - "127.0.0.1:3000:3000"
    command: sh -c "npm install --legacy-peer-deps --force && npm start"

  app_prod:
    build:
      context: .
      target: production
    ports:
      - "127.0.0.1:80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    init: true
    read_only: true

volumes:
  node_modules:
  build: